CaseNatixis/force-app/main/default/objects/Object_A__c/Object_A__c.object-meta.xml
<CustomObject>
    <label>Object A</label>
    <nameField>
        <label>Object A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>As</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CaseNatixis/force-app/main/default/objects/Object_B__c/Object_B__c.object-meta.xml
<CustomObject>
    <label>Object B</label>
    <nameField>
        <label>Object B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CaseNatixis/force-app/main/default/objects/Object_B__c/fields/Object_A__c.field-meta.xml
<CustomField>
    <fullName>Object_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object A</label>
    <referenceTo>Object_A__c</referenceTo>
    <relationshipLabel>Bs</relationshipLabel>
    <relationshipName>Bs</relationshipName>
    <type>Lookup</type>
</CustomField>

CaseNatixis/force-app/main/default/objects/Object_C__c/Object_C__c.object-meta.xml
<CustomObject>
    <label>Object C</label>
    <nameField>
        <label>Object C Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CaseNatixis/force-app/main/default/objects/Object_C__c/fields/Object_B__c.field-meta.xml
<CustomField>
    <fullName>Object_B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object B</label>
    <referenceTo>Object_B__c</referenceTo>
    <relationshipLabel>Cs</relationshipLabel>
    <relationshipName>Cs</relationshipName>
    <type>Lookup</type>
</CustomField>

CaseNatixis/force-app/main/default/classes/RelatedRecordsTableController.cls
public with sharing class RelatedRecordsTableController {   
    @AuraEnabled(cacheable=true)
    public static List<recordSummary> getRecordList(Id recId) {
        System.debug('recordId==> ' + recId);
        List<recordSummary> returnList = new List<recordSummary>();
        
        List<Object_B__c> objBList =  [SELECT Id, Name, CreatedDate,
                                      (select Id, Name, CreatedDate from Cs__r) FROM Object_B__c WHERE Object_A__c =: recId];
        
        for (Object_B__c itemB : objBList) {                   
            recordSummary tt = new recordSummary(itemB.Id, itemB.Name, itemB.createdDate);
            if(!returnList.contains(tt)) returnList.add(tt);
            
            for (Object_C__c ctt : itemB.Cs__r) {
                recordSummary newCtt = new recordSummary(ctt.Id, ctt.Name, ctt.createdDate);
                if(!returnList.contains(newCtt)) returnList.add(newCtt);
            }
        }
       // System.debug('return list:  ');
       // System.debug(JSON.serialize(returnList));
        return returnList;
    }  
    
    public class recordSummary {
        @AuraEnabled public Id recordId {get; set;}
        @AuraEnabled public String recordName {get; set;}
        @AuraEnabled public Datetime createdDate {get; set;}
        
        public recordSummary(Id recordId, String accountName, Datetime createdDate){
            this.recordId = recordId;
            this.recordName = accountName;
            this.createdDate = createdDate;            
        }
    }
    
}